/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Index } from "./Index";
import { IndexCountArgs } from "./IndexCountArgs";
import { IndexFindManyArgs } from "./IndexFindManyArgs";
import { IndexFindUniqueArgs } from "./IndexFindUniqueArgs";
import { DeleteIndexArgs } from "./DeleteIndexArgs";
import { IndexService } from "../index.service";
@graphql.Resolver(() => Index)
export class IndexResolverBase {
  constructor(protected readonly service: IndexService) {}

  async _indicesMeta(
    @graphql.Args() args: IndexCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Index])
  async indices(@graphql.Args() args: IndexFindManyArgs): Promise<Index[]> {
    return this.service.indices(args);
  }

  @graphql.Query(() => Index, { nullable: true })
  async index(
    @graphql.Args() args: IndexFindUniqueArgs
  ): Promise<Index | null> {
    const result = await this.service.index(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Index)
  async deleteIndex(
    @graphql.Args() args: DeleteIndexArgs
  ): Promise<Index | null> {
    try {
      return await this.service.deleteIndex(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
